### ISSUE TITLE
[SP5] Deploy SimpleSat survey app

### ISSUE THREAD

**Issue by sandysaille** [prontotools/simplesat#18]
As a Pronto Tools, I want to deploy SimpleSat so that other parties can have a look.

**Exit Criteria**
- [x] Have SimpleSat app deployed on Github Pages as a subfolder
- [x] Have 1 subfolder for each layout (total 5 subfolders) i.e. prontotols.github.io/simplesat/a

**Comment by lukyth** [comment]
It's now deploying on [Heroku](https://simplesat.herokuapp.com) instead of GitHub page.
