### ISSUE TITLE
[SP1]Install hotjar to survey layouts 

### ISSUE THREAD

**Issue by sandysaille** [prontotools/simplesat#31]
As a Pronto Tool, I want to install hotjar to my surveys so that we can see what users are doing.

**Exit Criteria**
- [x] have hotjar installed on surveys

**Tasks**

* Place hotjar script
* Test to make it works

**Comment by gomgam** [comment]
@corydbrown 
Could you please send us a hotjar js script?

**Comment by corydbrown** [comment]
@gomgam Here you go:

```
<!-- Hotjar Tracking Code for simplesat.herokuapp.com -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:272282,hjsv:5};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');
</script>
```

This is for simplesat.herokuapp.com. Let me know if I need to change the domain in hotjar. Thank you!

**Comment by gomgam** [comment]
@corydbrown 
Done, please review: https://simplesat.herokuapp.com/
