### ISSUE TITLE
[SP5][Task] Slider with Image

### ISSUE THREAD

**Issue by sandysaille** [prontotools/simplesat#8]
As developer, I want my survey to have different style, so that Buddy can have fun and give me feedback.

**Component name `ImageSlider`**

**Exit Criteria**
- [ ] Slide slider, image changes
- [ ] Have two sliders showing different images ranges to compare which one is better

**Note**
* Update how to render

Sliders ranges:

0-0.9|1-1.9|2-2.9|3-3.9|4-4.9|5-5.9|6-6.9|....9-9.0|10
0-0.4|0.5-1.4|1.5-2.4|2.5-3.4|3.5-4.4|....|8.5-9.4|9.5-10

**Comment by zkan** [comment]
KISS version: https://zkan.github.io/try-react/

**Comment by oy-np** [comment]
Create two image sliders:

* 0-0.9|1-1.9|2-2.9|3-3.9|4-4.9|5-5.9|6-6.9|....9-9.0|10
* 0-0.4|0.5-1.4|1.5-2.4|2.5-3.4|3.5-4.4|....|8.5-9.4|9.5-10
